./cal_chrom_interaction_score.sh Aardvark
./cal_chrom_interaction_score.sh Asian_elephant
./cal_chrom_interaction_score.sh Australian_echidna
./cal_chrom_interaction_score.sh Brown_bat
./cal_chrom_interaction_score.sh Burmese_python
./cal_chrom_interaction_score.sh Cheetah
./cal_chrom_interaction_score.sh Chicken
./cal_chrom_interaction_score.sh Chinese_alligator
./cal_chrom_interaction_score.sh Chinese_pangolin
./cal_chrom_interaction_score.sh Crag_lizard
./cal_chrom_interaction_score.sh Donkey
./cal_chrom_interaction_score.sh Emu
./cal_chrom_interaction_score.sh Eurasian_nightjar
./cal_chrom_interaction_score.sh European_otter
./cal_chrom_interaction_score.sh European_rabbit
./cal_chrom_interaction_score.sh Fruit_bat
./cal_chrom_interaction_score.sh Giant_anteater
./cal_chrom_interaction_score.sh Gray_squirrel
./cal_chrom_interaction_score.sh Great_bustard
./cal_chrom_interaction_score.sh Hooded_crow
./cal_chrom_interaction_score.sh Human
./cal_chrom_interaction_score.sh Killer_whale
./cal_chrom_interaction_score.sh Leopard_gecko
./cal_chrom_interaction_score.sh Monk_parakeet
./cal_chrom_interaction_score.sh Mouse
./cal_chrom_interaction_score.sh Pig
./cal_chrom_interaction_score.sh Platypus
./cal_chrom_interaction_score.sh Rhesus_macaque
./cal_chrom_interaction_score.sh Sea_snake
./cal_chrom_interaction_score.sh Sea_turtle
./cal_chrom_interaction_score.sh Sheep
./cal_chrom_interaction_score.sh Siamese_crocodile
./cal_chrom_interaction_score.sh Softshell_turtle
./cal_chrom_interaction_score.sh Tasmanian_devil
./cal_chrom_interaction_score.sh Whip_snake
