#!/bin/bash
#SBATCH -J Chicken
#SBATCH -p cpu
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --output=Chicken.o
#SBATCH --error=Chicken.e

chainMergeSort /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chr5/*.chain > /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr5.chain
chainPreNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr5.chain /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr5.pre.chain
chainNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr5.pre.chain -minSpace=1 /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes stdout /dev/null | netSyntenic stdin /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/net/chr5.net
chainMergeSort /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chr22/*.chain > /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr22.chain
chainPreNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr22.chain /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr22.pre.chain
chainNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr22.pre.chain -minSpace=1 /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes stdout /dev/null | netSyntenic stdin /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/net/chr22.net
chainMergeSort /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chr15/*.chain > /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr15.chain
chainPreNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr15.chain /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr15.pre.chain
chainNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr15.pre.chain -minSpace=1 /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes stdout /dev/null | netSyntenic stdin /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/net/chr15.net
chainMergeSort /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chr1/*.chain > /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr1.chain
chainPreNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr1.chain /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr1.pre.chain
chainNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr1.pre.chain -minSpace=1 /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes stdout /dev/null | netSyntenic stdin /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/net/chr1.net
chainMergeSort /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chr17/*.chain > /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr17.chain
chainPreNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr17.chain /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr17.pre.chain
chainNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr17.pre.chain -minSpace=1 /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes stdout /dev/null | netSyntenic stdin /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/net/chr17.net
chainMergeSort /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chr10/*.chain > /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr10.chain
chainPreNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr10.chain /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr10.pre.chain
chainNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr10.pre.chain -minSpace=1 /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes stdout /dev/null | netSyntenic stdin /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/net/chr10.net
chainMergeSort /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chr12/*.chain > /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr12.chain
chainPreNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr12.chain /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr12.pre.chain
chainNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr12.pre.chain -minSpace=1 /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes stdout /dev/null | netSyntenic stdin /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/net/chr12.net
chainMergeSort /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chr18/*.chain > /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr18.chain
chainPreNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr18.chain /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr18.pre.chain
chainNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr18.pre.chain -minSpace=1 /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes stdout /dev/null | netSyntenic stdin /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/net/chr18.net
chainMergeSort /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chr21/*.chain > /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr21.chain
chainPreNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr21.chain /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr21.pre.chain
chainNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr21.pre.chain -minSpace=1 /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes stdout /dev/null | netSyntenic stdin /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/net/chr21.net
chainMergeSort /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chr20/*.chain > /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr20.chain
chainPreNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr20.chain /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr20.pre.chain
chainNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr20.pre.chain -minSpace=1 /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes stdout /dev/null | netSyntenic stdin /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/net/chr20.net
chainMergeSort /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chr11/*.chain > /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr11.chain
chainPreNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr11.chain /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr11.pre.chain
chainNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr11.pre.chain -minSpace=1 /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes stdout /dev/null | netSyntenic stdin /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/net/chr11.net
chainMergeSort /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chr13/*.chain > /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr13.chain
chainPreNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr13.chain /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr13.pre.chain
chainNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr13.pre.chain -minSpace=1 /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes stdout /dev/null | netSyntenic stdin /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/net/chr13.net
chainMergeSort /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chr6/*.chain > /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr6.chain
chainPreNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr6.chain /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr6.pre.chain
chainNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr6.pre.chain -minSpace=1 /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes stdout /dev/null | netSyntenic stdin /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/net/chr6.net
chainMergeSort /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chr19/*.chain > /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr19.chain
chainPreNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr19.chain /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr19.pre.chain
chainNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr19.pre.chain -minSpace=1 /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes stdout /dev/null | netSyntenic stdin /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/net/chr19.net
chainMergeSort /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chr7/*.chain > /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr7.chain
chainPreNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr7.chain /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr7.pre.chain
chainNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr7.pre.chain -minSpace=1 /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes stdout /dev/null | netSyntenic stdin /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/net/chr7.net
chainMergeSort /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chr8/*.chain > /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr8.chain
chainPreNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr8.chain /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr8.pre.chain
chainNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr8.pre.chain -minSpace=1 /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes stdout /dev/null | netSyntenic stdin /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/net/chr8.net
chainMergeSort /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chrX/*.chain > /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chrX.chain
chainPreNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chrX.chain /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chrX.pre.chain
chainNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chrX.pre.chain -minSpace=1 /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes stdout /dev/null | netSyntenic stdin /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/net/chrX.net
chainMergeSort /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chr9/*.chain > /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr9.chain
chainPreNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr9.chain /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr9.pre.chain
chainNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr9.pre.chain -minSpace=1 /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes stdout /dev/null | netSyntenic stdin /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/net/chr9.net
chainMergeSort /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chr2/*.chain > /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr2.chain
chainPreNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr2.chain /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr2.pre.chain
chainNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr2.pre.chain -minSpace=1 /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes stdout /dev/null | netSyntenic stdin /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/net/chr2.net
chainMergeSort /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chr14/*.chain > /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr14.chain
chainPreNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr14.chain /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr14.pre.chain
chainNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr14.pre.chain -minSpace=1 /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes stdout /dev/null | netSyntenic stdin /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/net/chr14.net
chainMergeSort /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chr3/*.chain > /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr3.chain
chainPreNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr3.chain /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr3.pre.chain
chainNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr3.pre.chain -minSpace=1 /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes stdout /dev/null | netSyntenic stdin /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/net/chr3.net
chainMergeSort /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chr4/*.chain > /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr4.chain
chainPreNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr4.chain /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr4.pre.chain
chainNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr4.pre.chain -minSpace=1 /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes stdout /dev/null | netSyntenic stdin /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/net/chr4.net
chainMergeSort /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chr16/*.chain > /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr16.chain
chainPreNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr16.chain /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr16.pre.chain
chainNet /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/chain/chr16.pre.chain -minSpace=1 /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Human.sizes /slurm/home/zju/zhanglab/liujing/Project/Amniote/Chrom/Chicken.sizes stdout /dev/null | netSyntenic stdin /slurm/home/zju/zhanglab/liujing/Project/Amniote/Lastz_align/Chicken/net/chr16.net
