./ALG_connection_cal.sh Aardvark 0.5
./ALG_connection_cal.sh Asian_elephant 0.5
./ALG_connection_cal.sh Australian_echidna 0.5
./ALG_connection_cal.sh Brown_bat 0.5
./ALG_connection_cal.sh Burmese_python 0.5
./ALG_connection_cal.sh Cheetah 0.5
./ALG_connection_cal.sh Chicken 0.5
./ALG_connection_cal.sh Chinese_alligator 0.5
./ALG_connection_cal.sh Chinese_pangolin 0.5
./ALG_connection_cal.sh Crag_lizard 0.5
./ALG_connection_cal.sh Donkey 0.5
./ALG_connection_cal.sh Emu 0.5
./ALG_connection_cal.sh Eurasian_nightjar 0.5
./ALG_connection_cal.sh European_otter 0.5
./ALG_connection_cal.sh European_rabbit 0.5
./ALG_connection_cal.sh Fruit_bat 0.5
./ALG_connection_cal.sh Giant_anteater 0.5
./ALG_connection_cal.sh Gray_squirrel 0.5
./ALG_connection_cal.sh Great_bustard 0.5
./ALG_connection_cal.sh Hooded_crow 0.5
./ALG_connection_cal.sh Human 0.5
./ALG_connection_cal.sh Killer_whale 0.5
./ALG_connection_cal.sh Leopard_gecko 0.5
./ALG_connection_cal.sh Monk_parakeet 0.5
./ALG_connection_cal.sh Mouse 0.5
./ALG_connection_cal.sh Panther_chameleon 0.5
./ALG_connection_cal.sh Pig 0.5
./ALG_connection_cal.sh Platypus 0.5
./ALG_connection_cal.sh Rhesus_macaque 0.5
./ALG_connection_cal.sh Sea_snake 0.5
./ALG_connection_cal.sh Sea_turtle 0.5
./ALG_connection_cal.sh Sheep 0.5
./ALG_connection_cal.sh Siamese_crocodile 0.5
./ALG_connection_cal.sh Softshell_turtle 0.5
./ALG_connection_cal.sh Tasmanian_devil 0.5
./ALG_connection_cal.sh Tropical_frog 0.5
./ALG_connection_cal.sh Whip_snake 0.5
