perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Aardvark.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Asian_elephant.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Australian_echidna.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Brown_bat.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Burmese_python.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Cheetah.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Chicken.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Chinese_alligator.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Chinese_pangolin.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Crag_lizard.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Donkey.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Emu.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Eurasian_nightjar.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.European_otter.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.European_rabbit.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Fruit_bat.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Giant_anteater.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Gray_squirrel.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Great_bustard.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Hooded_crow.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Human.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Killer_whale.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Leopard_gecko.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Monk_parakeet.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Mouse.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Panther_chameleon.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Pig.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Platypus.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Rhesus_macaque.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Sea_snake.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Sea_turtle.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Sheep.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Siamese_crocodile.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Softshell_turtle.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Tasmanian_devil.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Tropical_frog.chrom_percent.txt
perl cal_ALG_ALG_percentage.pl Amniote.Human.ALG_type.r2 Amniote.Whip_snake.chrom_percent.txt

