./EBR_detection.sh Aardvark 0.05
./EBR_detection.sh Asian_elephant 0.05
./EBR_detection.sh Australian_echidna 0.05
./EBR_detection.sh Brown_bat 0.05
./EBR_detection.sh Burmese_python 0.05
./EBR_detection.sh Cheetah 0.05
./EBR_detection.sh Chicken 0.05
./EBR_detection.sh Chinese_alligator 0.05
./EBR_detection.sh Chinese_pangolin 0.05
./EBR_detection.sh Crag_lizard 0.05
./EBR_detection.sh Donkey 0.05
./EBR_detection.sh Emu 0.05
./EBR_detection.sh Eurasian_nightjar 0.05
./EBR_detection.sh European_otter 0.05
./EBR_detection.sh European_rabbit 0.05
./EBR_detection.sh Fruit_bat 0.05
./EBR_detection.sh Giant_anteater 0.05
./EBR_detection.sh Gray_squirrel 0.05
./EBR_detection.sh Great_bustard 0.05
./EBR_detection.sh Hooded_crow 0.05
./EBR_detection.sh Human 0.05
./EBR_detection.sh Killer_whale 0.05
./EBR_detection.sh Leopard_gecko 0.05
./EBR_detection.sh Monk_parakeet 0.05
./EBR_detection.sh Mouse 0.05
./EBR_detection.sh Panther_chameleon 0.05
./EBR_detection.sh Pig 0.05
./EBR_detection.sh Platypus 0.05
./EBR_detection.sh Rhesus_macaque 0.05
./EBR_detection.sh Sea_snake 0.05
./EBR_detection.sh Sea_turtle 0.05
./EBR_detection.sh Sheep 0.05
./EBR_detection.sh Siamese_crocodile 0.05
./EBR_detection.sh Softshell_turtle 0.05
./EBR_detection.sh Tasmanian_devil 0.05
./EBR_detection.sh Whip_snake 0.05
